name: ci 
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Automatically handles caching for you!
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Matches your local environment

      - name: Install dependencies
        # uv sync looks for your pyproject.toml / uv.lock
        run: uv sync --frozen

      - name: Deploy MkDocs
        # Use 'uv run' to execute mkdocs within the synced environment
        run: uv run mkdocs gh-deploy --force